trigger:
- master

pool:
  vmImage: ubuntu-latest

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version 
    - bash: mvn -version 
    - bash: ls -R $(Build.ArtifactStagingDirectory)

  # - job: SecondJob
  #   steps:
  #   - bash: echo Build SecondJob
# - stage: Dev
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo Build FirstJob
#   - job: SecondJob
#     steps:
#     - bash: echo Build SecondJob
#        dependsOn:Build
# - stage: DevDeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo Build FirstJob
#   - job: SecondJob
#     steps:
#     - bash: echo Build SecondJob
#        dependsOn:FirstJob
# - stage: QADeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo Build FirstJob
#   - job: SecondJob
#     steps:
#     - bash: echo Build SecondJob  


